### ISSUE TITLE
participant name: in topology

### ISSUE THREAD

**Issue by Toddelismyname** [precice-forschungsprojekt/precice-generate#126]
Instead of having:
```yaml
participants:
    Fluid: SU2
    Solid: Calculix
```

We now want:
```yaml
participants:
  - name: Fluid
    solver: SU2
  - name: Solid
    solver: Calculix
```

Implement that. That involves:
- updating the code
- updating example topologies
- update schema
