### ISSUE TITLE
topology does not generate receive mesh element

### ISSUE THREAD

**Issue by orlandoisepic** [precice-forschungsprojekt/precice-generate#142]
**Describe the bug**

When trying to create a config from a correct (at least I think) topology.yaml, the participants and coupling schemes are created according to the topology. However, the receive mesh tag does not get generated in the participant who is specifying a mapping. 

**To Reproduce**

```yaml
coupling-scheme:
  time-window-size: 0.01
  max-time: "0.3"
  coupling: serial
participants:
  - name: Generator
    solver: "SolverA"
  - name: Propagator
    solver: "SolverB"
exchanges:
  - from: Generator
    from-patch: interface
    to: Propagator
    to-patch: solid
    data: Force
    type: weak
    data-type: scalar
```

running  `precice-gen -f ` with this topology will create a precice config with a write-mapping defined by "Generator", from Generator-Mesh to Propagator-Mesh, but Generator does not receive Propagator-Mesh. This means that `precice-tools check` returns an error, because the mapping is invalid.

**Expected behavior**
There should be a receive-mesh tag on Generator.

This is the resulting config:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<precice-configuration>
    <data:vector name="Force"/>

    <mesh name="Generator-Mesh" dimensions="3">
        <use-data name="Force"/>
    </mesh>

    <mesh name="Propagator-Mesh" dimensions="3">
        <use-data name="Force"/>
    </mesh>

    <participant name="Generator">
        <provide-mesh name="Generator-Mesh"/>
<!-- <receive-mesh name="Propagator-Mesh" from="Propagator" /> THIS LINE IS MISSING -->
        <write-data name="Force" mesh="Generator-Mesh"/>

        <mapping:nearest-neighbor
            direction="write"
            from="Generator-Mesh"
            to="Propagator-Mesh"
            constraint="conservative"
         />
    </participant>

    <participant name="Propagator">
        <provide-mesh name="Propagator-Mesh"/>

        <read-data name="Force" mesh="Propagator-Mesh"/>
    </participant>

    <m2n:sockets acceptor="Generator" connector="Propagator" exchange-directory=".."/>

    <coupling-scheme:serial-explicit>
        <participants first="Generator" second="Propagator"/>
        <max-time value="0.3"/>
        <time-window-size value="0.01"/>

        <exchange data="Force" mesh="Propagator-Mesh" from="Generator" to="Propagator"/>
    </coupling-scheme:serial-explicit>
</precice-configuration>

```
