### ISSUE TITLE
How should the new topology look like ?

### ISSUE THREAD

**Issue by Toddelismyname** [precice-forschungsprojekt/precice-generate#29]
**Short description**

**Details**
This is needed currently but could be confusing if you need to enter the stuff into an element that wont exists in the config.
Current code
```yaml
simulation:
    timesteps: 30
    timestep-length: 1e-3
    steady-state: False
    accuracy: medium
```
When i for example put in code like this:

```yaml
meshes:
  - name: Fluid-Mesh
    dimensions: 2
    data: 
      - Temperature
      - Heat-Flux
```
      
I get the following error:
`Traceback (most recent call last):
  File "c:\Users\...\Desktop\precice\Forschungsprojekt\precice-structure-generator\FileGenerator.py", line 117, in <module>
    fileGenerator.generate_precice_config()
  File "c:\Users\...\Desktop\precice\Forschungsprojekt\precice-structure-generator\FileGenerator.py", line 38, in generate_precice_config
    self.user_ui.init_from_yaml(config, self.mylog)
  File "c:\Users\...\Desktop\precice\Forschungsprojekt\precice-structure-generator\controller_utils\ui_struct\UI_UserInput.py", line 30, in init_from_yaml 
    simulation_info = etree["simulation"]
KeyError: 'simulation'`

Which is understanable because the simulation tag is missing.
**Subtasks**
- [ ] ...

**Dependencies**
This task depends on ... to be finished
