### ISSUE TITLE
Benjamins Corrections (v2)

### ISSUE THREAD

**Issue by Toddelismyname** [precice-forschungsprojekt/precice-generate#57]
**Short description**
https://github.com/precice-forschungsprojekt/precice-structure-generator/pull/55#issue-2792322250
new topology:
```yaml
coupling-scheme:
    max-time: 1e-1 # used for max-time in all coupling schemes
    time-window-size: 1e-3 # used as time-window-size in all coupling schemes (future problem: how to handle different time-window-sizes) 
    relative-accuracy: 1e-4 # used to create relative-convergence-measure tags where necessary
participants:
    Fluid: SU2 # "Fluid" is the name of the participant, "SU2" the solver. Here, the solver name is only used for the folder name
    Solid: Calculix
exchanges:
    - from: Fluid
      from-patch: interface
      to: Solid
      to-patch: surface
      data: Force
      type: strong # if there is at least one strong exchange between two participants in each direction, then we need an implicit coupling scheme
    - from: Solid
      from-patch: surface
      to: Fluid
      to-patch: interface
      data: Displacement
      type: strong
```
**Details**

**Subtasks**
- [x] update topology "reading" to new from above 
    - [x] ~~start from scratch => [branch](https://github.com/precice-forschungsprojekt/precice-structure-generator/tree/work/karlo/new-precice-config-generation)~~ this branch did update controller code too
    - [x] update controller code => #60
- [x] make generation for example 1 work
- [x] run sh as "you need to do something here" fixed via #59

- [x] questions:
  - [x] >=1 strong type => implicit coupling. What with the rest ?
     - type is not used currently => siehe unten
  - [x] Benjamins correction adapter config uses partipant name instead of data name. Intended ? => no fix it => #66 
  - [x] Should we update the naming of folders for adapter config to name-solver or is it fine with just name ? => yes => #67 
  - [x] Is this [comment](https://github.com/precice-forschungsprojekt/precice-structure-generator/issues/28) valid for all stuff not implemented in controller ? => close and implement stuff when needed for examples
  - [x] license for project ? => same license as config checker => #85 
  - [x] What should we put in ReadMe

### TO DO
- [x] dev docs tools=> pre commit hook use to reformat config See #65 
- [x] fix the issue of example 1 where exchange (and acceleration) uses wrong mesh 
  - help: https://precice.org/configuration-coupling-mesh-exchange.html
  - #73 
- [x] strong in both implicit otherwise explicit => #83 
- [x] create more examples from tutorials (outdated) heat-exchange, multiple participants => #81 
- [x] create topology schema => See this branch [json-schema-for-topology](https://github.com/precice-forschungsprojekt/precice-structure-generator/tree/work/toddel/json-schema-for-topology)

- Should we rename the backend of postprocessing to acceleration like it was done in this branch ? 903b21fb1b061c5e4645f3a1209e714bb5e51281 and 797ac58a0418be50a591c4c044930738752581c0
