### ISSUE TITLE
New Topology update existing code

### ISSUE THREAD

**Issue by Toddelismyname** [precice-forschungsprojekt/precice-generate#60]
**Short description**
Goal is to generate a precice config like this: [precice-config](https://github.com/precice-forschungsprojekt/precice-structure-generator/blob/main/controller_utils/examples/1/precice-config.xml)
According to the new topology from example 1:
```yaml
coupling-scheme:
    max-time: 1e-1 # used for max-time in all coupling schemes
    time-window-size: 1e-3 # used as time-window-size in all coupling schemes (future problem: how to handle different time-window-sizes) 
    relative-accuracy: 1e-4 # used to create relative-convergence-measure tags where necessary
participants:
    Fluid: SU2 # "Fluid" is the name of the participant, "SU2" the solver. Here, the solver name is only used for the folder name
    Solid: Calculix
exchanges:
    - from: Fluid
      from-patch: interface
      to: Solid
      to-patch: surface
      data: Force
      type: strong # if there is at least one strong exchange between two participants in each direction, then we need an implicit coupling scheme
    - from: Solid
      from-patch: surface
      to: Fluid
      to-patch: interface
      data: Displacement
      type: strong
```

To compare [old topology](https://github.com/precice-forschungsprojekt/precice-structure-generator/blob/78d363ae0d36f62a2212d64f6148d68744fad9fd/controller_utils/examples/1/topology.yaml):
```yaml
simulation:
    timesteps: 20
    time-window-size: 1e-3
    steady-state: False
    accuracy: medium

participants:
    SU2_CFD:
        solver: SU2
        solver-type: SU2_CFD

    Calculix:
        solver: Calculix
        solver-type: NL

couplings:
    - fsi:
        structure:
            name: Calculix
            interface: interface
        fluid:
            name: SU2_CFD
            interface: interface
```

**Subtasks**
- [x] Get things like "time-window-size" from `coupling-scheme` instead of `simulation`
- [x] Adjust participants to 1 liner of solver+name
- [x] Adjust old `couplings` to new `exchanges`
   - ~~partly working as of [commit](https://github.com/precice-forschungsprojekt/precice-structure-generator/commit/d3087171f0ee031fd3c2d05c97321f9b13461943) => read and write data gets created that i dont need. Check "PS_PreCICEConfig.py" from line 233 on to continue~~ => Used Karlos implementation  and added naming stuff from branch here
- [x] Update test to not fail anymore ?
